FROM node:16.17.1-alpine as development

WORKDIR /usr/src/app

COPY package.json yarn.lock ./

RUN yarn install --production=false

COPY . .

RUN yarn build:import

FROM namxle/ubuntu:18.04 as production

WORKDIR /usr/src/app

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

COPY package.json yarn.lock ./

RUN yarn install --production=false

COPY . .

RUN yarn build:import

