FROM node:16.17.1-alpine as development

WORKDIR /usr/src/app

COPY package.json yarn.lock ./

RUN yarn install --production=false

COPY . .

RUN yarn build:vcf

FROM namxle/vep:latest as production

WORKDIR /home/ubuntu/genetics

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

COPY package.json yarn.lock ./

RUN source $NVM_DIR/nvm.sh && \
    nvm use default && \
    yarn install --production=false

COPY . .

RUN yarn build:vcf

# CMD ["node", "/home/ubuntu/genetics/dist/apps/vcf-analyzer/main"]